########## POSTS ##########

### GET all posts
GET http://localhost:3000/posts





### GET a post by its id
GET http://localhost:3000/posts/5db0cc8025a5df4268488c30





### POST a post
POST http://localhost:3000/posts
Content-Type: multipart/form-data; boundary=b0UNd4rY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRiMGM0MzBiNzRlYmIyMDYwYmI0NmY0IiwiaWF0IjoxNTcxODY1ODU2LCJleHAiOjE1NzE4Njk0NTZ9.BtwoXaiy55p-9F554SUO2_9w44n89oWMtGmiMO1lsA4

--b0UNd4rY
Content-Disposition: form-data; name="image"; filename="logo Centrale Marseille.png";
Content-Type: image/png

< x:\Images\logo Centrale Marseille.png
--b0UNd4rY
Content-Disposition: form-data; name="description"

repudiandae veniam quaerat sunt sed alias aut fugiat sit autem sed est voluptatem omnis possimus esse voluptatibus quis est aut tenetur dolor neque
--b0UNd4rY--





### PATCH a post
PATCH http://localhost:3000/posts/5db0c51052915c3cd875d9a3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRiMGM0MzBiNzRlYmIyMDYwYmI0NmY0IiwiaWF0IjoxNTcxODY1ODU2LCJleHAiOjE1NzE4Njk0NTZ9.BtwoXaiy55p-9F554SUO2_9w44n89oWMtGmiMO1lsA4

{
  "description": "Et sunt sunt amicum quasi benevolentiae sunt modo quisque diligendi."
}




### DELETE a post by his id
DELETE http://localhost:3000/posts/5dad99c7c849c72fcc566028
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRiMGM0MzBiNzRlYmIyMDYwYmI0NmY0IiwiaWF0IjoxNTcxODY1ODU2LCJleHAiOjE1NzE4Njk0NTZ9.BtwoXaiy55p-9F554SUO2_9w44n89oWMtGmiMO1lsA4
