########## POSTS ##########

### GET all posts
GET http://localhost:3000/posts





### GET a post by its id
GET http://localhost:3000/posts/5dae31fd67efb930e05939bd





### POST a post
POST http://localhost:3000/posts
Content-Type: multipart/form-data; boundary=b0UNd4rY
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRhZGIzYTA2ZWEzYjQxZTY4NmY3YTI1IiwiaWF0IjoxNTcxNjk2MzYzLCJleHAiOjE1NzE2OTk5NjN9.YdWDjK9TStwsUzVx6MmnlT0iY1-rYXzFwz7jfR2ubnQ

--b0UNd4rY
Content-Disposition: form-data; name="image"; filename="logo Centrale Marseille.png";
Content-Type: image/png

< x:\Images\logo Centrale Marseille.png
--b0UNd4rY
Content-Disposition: form-data; name="description"

repudiandae veniam quaerat sunt sed alias aut fugiat sit autem sed est voluptatem omnis possimus esse voluptatibus quis est aut tenetur dolor neque
--b0UNd4rY--





### PATCH a post
PATCH http://localhost:3000/posts/5dae31fd67efb930e05939bd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNWRhZGIzYTA2ZWEzYjQxZTY4NmY3YTI1IiwiaWF0IjoxNTcxNjk3NDA4LCJleHAiOjE1NzE3MDEwMDh9.hhFF1cYquUxU25-Yb-wPmokKrTB2_vtDakOCMPEoCOU

{
  "description": "Et sunt sunt amicum quasi benevolentiae sunt modo quisque diligendi."
}




### DELETE a post by his id
DELETE http://localhost:3000/posts/5dad99c7c849c72fcc566028
