########## USERS ##########

### GET all users
GET http://localhost:3000/users





### GET a user by his id
GET http://localhost:3000/users/5dadb3a06ea3b41e686f7a25





### Signup a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "username": "LR LR",
  "email": "lrlr@gmail.com",
  "password": "123456"
}





### Log a user
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "login":"Madox",
  "password":"212121"
}





### PATCH a user
PATCH http://localhost:3000/users/5dadb3a06ea3b41e686f7a25
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZGFkYjNhMDZlYTNiNDFlNjg2ZjdhMjUiLCJ1c2VybmFtZSI6IkJydWgiLCJlbWFpbCI6ImJydWgxMjNAZ21haWwuY29tIiwiaWF0IjoxNTcxNjk1Njg2LCJleHAiOjE1NzE2OTkyODZ9.Q5QEM8de8NYHhNggUfeyv8L0BaafjvjvcFnIzXkSUro

{
  "username": "Madox"
}





### DELETE a user by his id
DELETE http://localhost:3000/users/5dadb2c2a4f24d2c08911486
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZGFjNmI0YWY3MmE2ZjBjNDQzY2VmN2EiLCJ1c2VybmFtZSI6IkphaCIsImVtYWlsIjoiamFoQGdtYWlsLmNvbSIsImlhdCI6MTU3MTY5Mjk3NywiZXhwIjoxNTcxNjk2NTc3fQ.fUl_idaVh0HejWoAQU0sHWRCL2aOStdvuajuZ9bhvl
